#ifndef IDS_H
#define IDS_H

// Main BG defines
#define NUMBERS 1

// Main sprite defines
#define LARGE_MARKER 2
enum {MARKER_1,
      MARKER_2_DOWNLEFT, MARKER_2_DOWNRIGHT, MARKER_2_HORIZONTAL, MARKER_2_VERTICAL,
      MARKER_3_DOWNLEFT, MARKER_3_DOWNRIGHT, MARKER_3_HORIZONTAL, MARKER_3_VERTICAL};

#endif
